[project]
name = "lithium"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "django ~=5.1",
  "django-allauth[openid,socialaccount] ~=65.2",
  "django-debug-toolbar ~=4.4",
  "crispy-bootstrap5 ~=2024.10",
  "gunicorn ~=23.0",
  "psycopg[binary] ~=3.2",
  "whitenoise ~=6.7",
]

[dependency-groups]
dev = [
  "factory-boy>=3.3.3",
  "pre-commit>=4.1.0",
  "pytest-django>=4.11.1",
  "ruff>=0.9.10",
  "typing_extensions ~=4.12",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"

[tool.ruff]
lint.select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "W",   # pycodestyle
  "B",   # bugbear
  "I",   # isort
  "RUF", # ruff
  "A",   # builtins
  "C4",  # comprehension
  "UP",  # pyupgrade
]

lint.ignore = [
  "E501", # ruff format handles line length
  "F401", # allow unused imports in the template
]

[tool.ruff.lint.per-file-ignores]
"**/migrations/*.py" = ["RUF012"] # ignore mutable class attributes
"tests/settings.py" = ["F403", "F405"] # ignore star imports
